name: Android CI

on:
  push:
    branches: [main, develop]
  workflow_dispatch:
  

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: lint

    - name: Upload Reports
      uses: actions/upload-artifact@v2
      with:
        name: Test-Reports
        path: app/build/reports/lint*
      if: always()

    - name: Generate Release APK
      run: ./gradlew <gradle-task>

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.RELEASE_STORE_FILE }}
        alias: ${{ secrets.RELEASE_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.RELEASE_STORE_PASSWORD }}
        keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}

    - uses: actions/upload-artifact@master
      with:
        name: release.apk
        path: ${{steps.sign_app.outputs.signedReleaseFile}}

    - uses: actions/upload-artifact@master
      with:
        name: mapping.txt
        path: app/build/outputs/mapping/release/mapping.txt
